### ISSUE TITLE
Support Python 3.4.

### ISSUE THREAD

**Issue by dotsdl** [datreant/datreant.core#10]
It's important that we support Python 3.4. The only barrier I see at the moment is related to unicode handling on the part of Pytables. For example, we get with Python 3.4:

```python
import datreant as dtr
t = dtr.Treant('treebeard')
t.tags.add('bark')
'bark' in t.tags()
>>> False
```
because `bark` is in unicode, but the 'bark' read from the file that's in the set of tags is of type ``byte``, which is a Python 2.7 style string. Opening the same Treant in Python 2.7 yields ``True`` for ``'bark' in t.tags()``.

This is related to https://github.com/PyTables/PyTables/issues/268. Until a cleaner solution appears there, we could wrap writes and reads to files to convert inputs and outputs of strings, but this might be a performance hit at this level.

**Comment by andreabedini** [comment]
@dotsdl could you please open another ticket at PyTables with an example of what doesn't work for you? I feel PyTables/PyTables#268 went a bit off track. Thanks.

**Comment by dotsdl** [comment]
@andreabedini will do. From the discussion on PyTables/PyTables#268  I think I saw there might be a possible solution at the PyTables level, although it would be a bit of work.

**Comment by andreabedini** [comment]
Thanks @dotsdl

**Comment by andreabedini** [comment]
I see your problem now, you put a `'bark'` and you get back a `b'bark'`.

```
In [4]: t.tags
Out[4]: <Tags([b'bark', b'bark', b'bark'])>

In [5]: 'bark' in t.tags
Out[5]: False

In [6]: b'bark' in t.tags
Out[6]: True

```

**Comment by dotsdl** [comment]
@andreabedini Yup. I think if there's not really an easy solution within PyTables given that Unicode strings are variable length, but I'll open an issue there to keep the discussion open anyhow. I'm sure I'm not the only one that's run into this issue.

As for `datreant`, I'll probably just wrap the HDF5 backends with code to convert strings on retrieval. It's nonideal since it's bound to break with non-ascii characters, but I think that's the best that can be done for now.

**Comment by andreabedini** [comment]
@dotsdl You are using fixed (byte-)size strings and the hdf5 file has some metadata `H5T_CSET_ASCII` that specifies the encoding 

      DATATYPE  H5T_COMPOUND {
         H5T_STRING {
            STRSIZE 55;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         } "tag";
      }
      DATASPACE  SIMPLE { ( 3 ) / ( H5S_UNLIMITED ) }
      DATA {
      (0): {
            "bark"
         }, {
            "bark"
         },
      (2): {
            "bark"
         }
      }

so PyTables clearly should do `bytesfromdisc.decode('ascii')` here before returning the data to you. So that's clearly our fault.

**Comment by dotsdl** [comment]
@andreabedini I added an issue that reproduces the problem at PyTables/Pytables#499. I think the solution you suggest will work, but I wonder if a more general one exists? We can continue the discussion there. Thanks for the help!

**Comment by dotsdl** [comment]
PyTables is no longer a dependency, and we've had working testing on Travis for all the major Python 3.x versions. Closing.
