### ISSUE TITLE
non intuitive behavior for `Treant.treants`

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.core#114]
I stumbled across this behavior today. I have  a top treant and treants spread in sub directories (not directly below the top directory). Then I see the following difference between `dtr.discover` and `Treant.treants`. 

``` python
# finds a treants
dtr.discover()

t = dtr.Treant('.')
# doesn't find any treant
t.treants
```

I see that this is because `t.treants` is initialized as a normal Bundle which doesn't search into the directories like `dtr.discover`.  I expected it though to work like `discover(t.path)` to find all sub treants.

Should we make that change?

**Comment by dotsdl** [comment]
@kain88-de ``Treant.treants`` has similar behavior to ``Treant.trees``, ``Treant.leaves``, and ``Treant.children``, giving only ``Treant`` objects that are inside the given ``Treant``, but not the ``Treant`` itself. I think this behavior is intuitive, but I'm also not completely happy with it myself. Does that make sense? I'm interested in alternatives.

**Comment by kain88-de** [comment]
My expectation is that `t.treants` is equivalent to `dtr.discover(t.abspath)`. But apparently it only shows only treants in the direct sub directories. I would find that `t.treant = t.discover` is more intuitive, but that others might have a different opinion.

**Comment by dotsdl** [comment]
Given [discussion in #112](https://github.com/datreant/datreant.core/issues/112#issuecomment-281758844) and here, I propose we remove ``Treant.treants`` completely. In addition to being confusing, it doesn't make as much sense for derived libraries like ``mdsynthesis``, with similar (but more flexible) functionality already given by ``datreant.core.discover`` and ``mdsynthesis.discover``. Agree?

**Comment by kain88-de** [comment]
Yes remove it.

**Comment by dotsdl** [comment]
Excellent. Will do now.
