### ISSUE TITLE
Leave may contain parent tree path twice

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.core#116]
I came across some weird path issues of tree and their leave objects today.  I'm not sure exactly what I need to do to reproduce the issue right now. I write everything I do down and describe the filesystem state as best as I can.

**Filesystem**:
I have a folder called `data` containing several analysis runs. This is a deep folder structure containing data for several simulations and analysis types usually with `data/protein/analysis`. Each `analysis` folder contains a treant object.

**datreant Code**:
1. Get a bundle with `b = dtr.discover('data')`
2. get a treant with `t = b[0]`
3. get a leaf with `l = t.tree['data/protein/analysis']`
4. `print l.abspath` will now return /top/path/data/protein/analysis/**data/protein/analysis**

As you can see the last leaf object points to a non existing path. I'm actually wondering why point 3 works. But the tree anyway doesn't show me the data folder in the treants (which i think it does in other treants)

**Comment by dotsdl** [comment]
You said each ``analysis`` folder is a ``Treant``, correct? In this case, the members of the ``Bundle``, ``b``, are each ``analysis`` folders, so doing

```python
t = b[0]
t.tree
```
would give you a ``Tree`` object pointing to the first ``analysis`` directory in your ``Bundle``, so doing:

```python
t.tree['data/protein/analysis']
```
gets you back a ``Leaf`` object to a leaf that probably doesn't exist with the path you describe. This behavior is what I'd expect, so I think the best question I can ask is: what are you trying to achieve?

**Comment by kain88-de** [comment]
> what are you trying to achieve?

I don't remember anymore.



> probably doesn't exist with the path you describe

I think I forgot that a tree can point to a non existing object just fine.
