### ISSUE TITLE
setup.cfg

### ISSUE THREAD

**Issue by rddaz2013** [datreant/datreant.core#129]
install_requires=['asciitree', 'pathlib2', 'scandir', 'six', 'fuzzywuzzy']

after python3.5 there is no need for 'scandir'

Is there a way to skip the requirement 'scandir' for >python3.4 in the setup.cfg ? 
Or better modify the import?

**Comment by kain88-de** [comment]
There isn't much you can do about that. setuptools doesn't take this into consideration. It doesn't hurt though. Does something not work for you currently with python 3.5

**Comment by dotsdl** [comment]
Until we drop support for Python < 3.5, we will still use ``scandir``. It doesn't hurt to continue using ``scandir`` until then. Does this satisfy your question, @rddaz2013?
