### ISSUE TITLE
Possible better names for Low-Level classes

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.core#134]
**Note**: I think @dotsdl already did a great job giving intuitive names to all classes and methods in datreant. There are some small things where I'm sometimes confused though. The following suggestions remove these confusions for me. It's OK if you don't agree with me on this subject.
After all there are three hard things in programming, naming and off-by-one errors.

-----------------------------------------------------

The names in the low level classes of datreant have been chosen based on the analogy of a physical tree with a filesystem tree.  Example picture of a file system tree.

![datreant](https://cloud.githubusercontent.com/assets/4302678/23339822/b200cc80-fc2a-11e6-8a1c-c801563df696.png)

*legend*: filled circle -> Folder, empty circle -> File

**Low level classes for filesystem manipulation**

*Tree*: A folder that may exist
*Leave*: A file that may exist
*View*: A collection of trees and leaves. Eg red & green marked areas

The member attributes of these classes though have been chosen with the Computer-Science model of a tree in mind. So `Tree.children` means all sub-nodes of a folder, eg Node 1,2,3 are children of node 0. And `Tree.parent` is the reverse relation ship, eg, 0 is the parent of 1,2,3.

I'm not overly happy with children and parent since there isn't an analogy in physical trees but it should be easy to understand none the less.  

# proposed changes to names

## Change *View* to *Forest*

The name *View* doesn't hold much meaning for me. The others have been chosen well and I can guess what the class is doing based on the name. I can't do that for *View*. I would suggest to rename that class to 

*Forest*: A collection of trees and leaves

That name tells me more that the class is a collection and it follows the common theme that classes
are named after physical tree equivalents.

EDITS
* fixed spelling "forrest" -> "forest" (@orbeckst 2017-02-27)

**Comment by richardjgowers** [comment]
I wouldn't intuitively think that I could keep leaves in a forest, only trees.  If anything, maybe Bundle which only holds treants should be the Forest and View becomes Collection (which implies it just collects *things*)
