### ISSUE TITLE
Drop use of uuids for Treants?

### ISSUE THREAD

**Issue by dotsdl** [datreant/datreant.core#135]
With the [removal of Groups](https://github.com/datreant/datreant.core/pull/130), there is now little need for ``Treant``s that have moved to be identifiable later by other objects in ``datreant.core``. The idea behind each ``Treant`` having a ``uuid`` was that even if they are moved they are identifiable, so something like a ``Group`` at least has some chance of finding its lost members. There's no point to this now.

I propose we remove the concept of a ``uuid`` entirely from ``Treant``s. We will simplify the state file to have the name ``Treant.json`` (or, if we want to go hidden, ``.Treant.json``). This makes ``Treant``s easier to copy around without worrying about objects like ``Bundle`` getting confused when two ``Treant``s have the same ``uuid``. The absolute path of a ``Treant`` will become its new unique identifier for ``Bundle``. It also becomes impossible on POSIX filesystems to create two ``Treant``s with the same directory.

There are downsides to this. The ``uuid`` is a (relatively) brief way to refer uniquely to a ``Treant``, so they are useful. They can still be used by users if desired by doing something like:

```python
import uuid
import datreant.core as dtr

t = dtr.Treant('sprout')
t.categories['uuid'] = uuid.uuid4()
```
so existing machinery that relies on these can still be used if desired.

Thoughts? If there's agreement here, I'd like to cut out the use of ``uuid``s quickly for inclusion in 0.8.0. This would be a big change that I think would simplify things greatly.

**Comment by kain88-de** [comment]
I'm not sure how you do it now. But I'm using a groupby to specify individual treants. I never used the uuid. This way I also know much better what simulation the treant refers to.

**Comment by dotsdl** [comment]
@kain88-de if you don't use ``uuid``s directly yourself, are you okay with removing them?

**Comment by kain88-de** [comment]
yeah I'm ok with removing them. You can wait a bit for the answer of the others if you like.

**Comment by richardjgowers** [comment]
So if I do move a Treant around, how do I hash it without a uuid?

**Comment by kain88-de** [comment]
Why do you need to hash it?

**Comment by richardjgowers** [comment]
So with a directory structure something like:
```
parameters_1
+-> p_1
+-> p_2
+-> p_3
parameters_2
+-> p_1
+-> p_2
+-> p_3
```
Where I calculate a value from each subdirectory.  If I then put these into a dictionary of `{treant: value from treant}`, without uuids this won't work

**Comment by kain88-de** [comment]
We can still put a uuid into the treant model to allow for this with `treant.uuid`. 

But I actually found using categories and groupby to be much better suited here. Assuming that you have a category with `treant.category['parameter_x'] = val_x` in each treant. Then just going for the simulations with `parameter_x` you can use.

```python
bundle = dtr.discover()
# dictionary with parameter_x values as keys and the treants as items
param_1_sims = bundle.groupby('parameter_x')
```

Or I think the second example is closer to what you want. I assume it can be made into a function that extracts the value into a dataframe in long table format.

```python
bundle = dtr.discover()
default_cols = bundle.categories.any.keys()
value_name = 'foo'
cols = default_cols.append([value_name, ])

df = pd.Dataframe(columns=cols)

for treant in bundle:
    # I'm not sure if this is correct if treants have different category values.
    df_dict = default_dict(None)
    for k in treant.categories: df_dict[k] = treant.categories[k]
    df_dict[value_name] = treant.data['value']
    df = df.append(pd.DataFrame(df_dict, ignore_index=True)
```

Then you can sort the value depending on the categories used with a groupby on the dataframe.

**Comment by richardjgowers** [comment]
I guess we can also just hash the path of the Treant to get something like what I need, ie make `Treant.__hash__ == hash(Treant.path)`

**Comment by ajasja** [comment]
@dotsdl What would be the benefits of removing the uiid?

I think being able to identify moved treants is a good feature, and a bit shorter file name does not bring much tangible improvements. I'm probably missing some internal code simplification that this will bring?

**Comment by kain88-de** [comment]
The uuids aren't really useful for us. The bundles we use now exclusively don't use the uuid feature to find moved treants. Most of us currently just so a bundle search and then a groupby on the bundle. it works also independent where the treant is as long as it is in the initial search path.
