### ISSUE TITLE
Need mechanism for updating file schema from previous versions

### ISSUE THREAD

**Issue by dotsdl** [datreant/datreant.core#18]
Closely related to Becksteinlab/MDSynthesis#36

Upon loading an existing Treant, the corresponding ``TreantFile`` class should do a version check between the version given by the state file and the current version of datreant. It should then run code that updates the schema to that used by the current version of datreant.

This will require:

1. an explicitly-documented schema spec for each ``TreantFile`` class, which can change each release
2. a mechanism for performing iterative updates to existing files; in other words, a file that was made with a very old version of datreant gets schema updates for each version of datreant it is behind, until it reaches the current one
3. the mechanism to update files needs to be stress-tested with its own set of unit tests; it should be robust enough to restart conversion of a file that is only half-converted to a new version, which might happen if the python session dies mid-conversion.

**Comment by orbeckst** [comment]
Is it desirable to have an automatic conversion (which presumably gets written back)? This can leave me in the situation where I cannot read files on an slightly older installation as soon as I dared looking at them with a newer version. This situation is more likely if you copy files between different systems.

**Comment by dotsdl** [comment]
@orbeckst that is a good point. I think it important that existing Treants continue to work for newer versions of `datreant` during development toward a 1.0 release, but that trying to maintain support for older Treants alongside newer Treants won't be easy (and with limited resources, perhaps ill-advised).

I think if we tried to do that it still wouldn't fix all of the problem, because if you installed a newer version of the library on your laptop, created some new Treants, then copied them to a remote server with an older version installed, they simply can't work. At best we can throw an exception when a Treant has a version mark newer than the library being used to read it.

This is similar to the situation with the Jupyter Notebook, where notebooks created with a new (major) version of the library won't be readable by an older version. The solution is always *upgrade your installation*. However, whenever the Jupyter Notebook reads a notebook from an older major version, it asks before updating it. I would love to be able to just throw a warning when an older Treant is read and everything still works anyway, but this means maintaining code that can still read the old versions. I don't think we should spend time on that right now.

I think the best we can do is try to make such schema changes seldom, and limit them only to major releases (0.x.0, until we hit 1.0). I'm optimistic that this will still work because the basic Treants `datreant` provides, `Treant` and `Group`, are minimal by design. That is, there is little that *could* be changed in either's backends.

Thoughts?

**Comment by orbeckst** [comment]
I agree with you that pre-1.0 pretty much anything is fair game (although of course one does not want to p***-off early adopters too much). Nevertheless, I would prefer an exception and a message that I have to upgrade instead of magic behind the scenes. That also decreases the burden on the developers because you can just write a simple conversion script and have the user run it instead of patching in lots of legacy format reading into the library.

**Comment by dotsdl** [comment]
> Nevertheless, I would prefer an exception and a message that I have to upgrade instead of magic behind the scenes.

Just to clarify, there are two cases here to consider:

1. A newer version of the library is installed, and a `Treant` created with a previous version is regenerated (loaded). What happens?
    1. The `Treant`'s internal schema are updated automatically to conform to the new version, and everything *just works*.
    2. An exception is raised and it tells you to regenerate the `Treant` with a specific keyword argument  (perhaps `update=True`?) for it to work. Doing this updates the schema to conform to the new version, but it is now incompatible with older versions in which the schema differs.

2. A `Treant` created with a newer version of the library is regenerated with an older release. What happens?
    1. An exception is raised, telling you that the `Treant` is from a newer version of the library, and that an upgrade of the library is necessary to read this version of the schema. Note, this will only happen if the schema actually changed between these versions.

For the second case there's only one clear thing to do. For the first, there's a couple options. I think both have their advantages, but I'm partial to the first because it requires less annoyance (so long as everything really does **just work**).

**Comment by dotsdl** [comment]
I moved this to the next milestone. We will not be trying to account for changes made to the schema during the pre-release period, since the versioning system itself changed during the splitting out of datreant from MDSynthesis. Since now there exists a clear version stamp for datreant objects and an additional, separate stamp for MDSynthesis objects, the mechanism we build has the pieces it needs to work.

**Comment by dotsdl** [comment]
Unneeded right now, so closing. May revisit if necessary in the future.
