### ISSUE TITLE
access data objects by 'subgroup'

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.core#23]
I would like to be able to access data objects also with subgroups. Assuming 'groups' are separated by a '/'. So I would create the Treant like this.

```python
import datreant as dtr

treant = dtr.Treant('observables')

treant.data.add('long_sim/obs_1', obs_1)
treant.data.add('long_sim/obs_2', obs_2)

treant.data.add('short_sims/1/obs_1', short_1_obs_1)
treant.data.add('short_sims/1/obs_2', short_1_obs_2)
treant.data.add('short_sims/1/obs_3', short_1_obs_3)

treant.data.add('short_sims/2/obs_1', short_2_obs_1)
treant.data.add('short_sims/2/obs_2', short_2_obs_2)
treant.data.add('short_sims/2/obs_3', short_2_obs_3)
```

Now it would be great If I could do something like this

```python
>>> long_sim = treant['long_sim']
>>> print(long_sim.data)
Data
====
'obs_1'
'obs_2'
```

I haven't found anything in the docs about this. Is there a possible query for this? Can groups be used for something like this?

**Comment by dotsdl** [comment]
@kain88-de no mechanism like you describe exists, but I think there's value in making it work this way. Perhaps a `DataSet` object that works kind of like `datreant.collections.Bundle` in gathering up data files it finds in a directory hierarchy and gives an interface to them and their metadata?

The mechanisms of dataset storage and retrieval isn't really set in stone yet (see for example #19), and I think the current implementation, though simple and straightforward (a good thing) doesn't generalize well to other file formats or perhaps more detailed ways of storing and pulling data.

**Comment by kain88-de** [comment]
Maybe this should work in a hierarchical way. The usage I outlined above is basically a hierarchical usage with the `__getitem__` method returning a treant object. This makes also sense since you are using the filesystem as an abstract self kinf of self describing data container. I'm not sure what would be the most comfortable way though. I'll play around with this library a bit more in the next few days and see if I can think of something.

**Comment by dotsdl** [comment]
I'm liking this more and more I I think about it. I'm currently working on the docs for the first actual release (0.6.0), and I think it makes sense to remove `Treant.__getitem__` as a shortcut for `Treant.data.__getitem__` in favor of a kind of subtree object, that may itself be a `Treant`. Will have to think some more about how this could work self-consistently, but I think it makes a lot of sense.

**Comment by kain88-de** [comment]
BTW since I came in need of it right now I wrote a small class doing exactly what I want.
It's far from perfect but maybe a start.

```python
class TreantView(object):
    def __init__(self, treant, include, exclude=None):
        self._treant = treant
        self._filter(include, exclude)
        
    def _filter(self, include, exclude=None):
        if exclude is None:
            exclude = []
        keys = [k for k in self._treant.data.keys() if \
                (np.all([w in k for w in include]) and
                (np.all([w not in k for w in exclude])))]
        self._keys = keys
    
    @property
    def data(self):
        class foo(object):
            _keys = self._keys
            
            def keys(self):
                return self._keys
        return foo()
        
    def __getitem__(self, item):
        if type(item) == int:
            return self._treant[self._keys[item]]
        elif type(item) == str:
            head = split(self._keys[0])[0]
            return self._treant[head + '/' + item]
        else:
            raise NotImplementedError('can only handle int and str')
```

**Comment by dotsdl** [comment]
Nice! Do you have a public branch somewhere that I can play with? I've been reflecting a lot on making generalized subtree interactions a central part of how `Treants` work, because I think this is really valuable. Still not sure what the best way to move forward is.

**Comment by kain88-de** [comment]
I only used an even hackier version so far in a private notebook. I have same ideas how this can be made to handle subtrees in a better manner and apply some filtering for the view.

**Comment by kain88-de** [comment]
I noticed that my view in the end does more then what I actually wanted in this issue. To track the new view-class I opened a new issue #30.

But this here is still useful. Although I think I can't implement this ontop of the current `Treant` objects.
I hope I have some time this week to look into converting the `Treant` object into a recursive tree.

**Comment by dotsdl** [comment]
This mechanism has landed in `develop`. `Treant`s are now a subclass of `Tree`, which is a directory in the filesystem (that may or may not exist). In practice, one can now do:

```python
import datreant.core as dtr
import datreant.data.attach

import pandas as pd

t = dtr.Treant('sprout')

t.data['roots/eins'] = pd.DataFrame(pd.np.random.randn(100, 3))
t.data['roots/zwei'] = pd.DataFrame(pd.np.random.randn(100, 3))
t.data['roots/drei'] = pd.DataFrame(pd.np.random.randn(100, 3))

t.draw()
> sprout/
   +-- Treant.839c7265-5331-4224-a8b6-c365f18b9997.json
   +-- roots/
       +-- zwei/
       |   +-- pdData.h5
       +-- drei/
       |   +-- pdData.h5
       +-- eins/
           +-- pdData.h5
  

tr = t['roots']

tr
> <Tree: 'sprout/roots'>

tr.draw()
> roots/
   +-- zwei/
   |   +-- pdData.h5
   +-- drei/
   |   +-- pdData.h5
   +-- eins/
       +-- pdData.h5

tr.data
> <Data(['drei', 'eins', 'zwei'])>

tr.data['zwei'].shape
> (100, 3)
```

The next step is to create the `View` object, which may very well serve as a base class for `Bundle`, that allows aggregation of `Tree` and `Leaf` objects (which don't refer to a state file, unlike a `Treant`).

Does this functionality close the issue?

**Comment by kain88-de** [comment]
Looks pretty good. I'll reopen it if I find anything wrong when I'm using it. Thanks
