### ISSUE TITLE
Create organization website, set up Travis to push development doc builds

### ISSUE THREAD

**Issue by dotsdl** [datreant/datreant.core#28]
[Read the Docs](http://datreant.readthedocs.org/) doesn't appear to play well with `setup.py` `install_requires`, which we want to keep so that dependencies get automatically handled with `setuptools` or `pip`. Even though we can mock our imports, keeping `install_requires` will pull the dependencies anyway, which fails the build.

Instead, it makes sense to create a website for the organization at http://datreant.org, the domain name for which I already own. We'll probably go the same route as http://mdanalysis.org with a simple Jekyll site, probably with a different color theme, and then set up travis to push development docs somewhere in the tree.

**Comment by dotsdl** [comment]
Note, we should probably do the same for [MDSynthesis](https://github.com/datreant/MDSynthesis)

**Comment by orbeckst** [comment]
For reference (as you already know): See MDAnalysis/mdanalysis#386 for how to make Travis build the docs and push to the gh-pages branch. If you do this for datreant and MDSynthesis, you will have the docs at http://datreant.org/datreant and http://datreant.org/MDSynthesis .

(Similarly, http://www.mdanalysis.org/mdanalysis ,  http://www.mdanalysis.org/GridDataFormats/ , http://www.mdanalysis.org/MDAnalysisTutorial/ --- they all use Travis and essentially the same script.)

**Comment by dotsdl** [comment]
Since ReadTheDocs now appears to support [conda environments](https://docs.readthedocs.org/en/latest/conda.html?highlight=conda) (in beta), we're going to give this a shot for the libraries under the datreant umbrella. It looks like this works, considering all the [blaze](http://blaze.pydata.org/) packages host their docs there. I think this is easier than trying to maintain a build scheme for all of our own docs, and keeps to the federated approach.

Open to opinions, as well as help on this front.

**Comment by dotsdl** [comment]
RTD works quite well. Closing.
