### ISSUE TITLE
Fancy indexing should work for Group.members and Bundle

### ISSUE THREAD

**Issue by dotsdl** [datreant/datreant.core#29]
It should be possible to get back a `Bundle` by using `numpy`-style fancy indexes on `Group.members` and `Bundle`, which could be lists of indices to return or boolean indexes. This currently does not work.

This issue was originally brought up in #25.

**Comment by orbeckst** [comment]
Yes, please!

**Comment by dotsdl** [comment]
This has finally landed in 85008be1da765758396bf6e32ec235f7aa464038. Indexing by name (#2) and by uuid also work. Note that boolean indexing only works when feeding in a numpy array, since lists are parsed recursively.
