### ISSUE TITLE
A static view that can be filtered/sorted should exists

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.core#30]
While I was looking for a solution to my problem in #23 I noticed that I actually want something
even more powerful. Just having a convenient access to a leave in the treant is not enough. I also want to be able to select special subsets of the leaves. An additional view class that can select specific subsets in a leave would solve that. I have made a [gist](https://gist.github.com/kain88-de/7dfcb53b9831411fd3d2) with an example implementation of a `TreantView` and how I use it.

**Comment by dotsdl** [comment]
I think this should generalize over more than what `Treant.data` deals in, in that a `Treant` should be able to function as a repository for any type of file but make it easier to work with them programmatically by filtering on the `Treant's` stored metadata, in particular `tags` and `categories`. Note that at the moment `Treant`'s `__getitem__` and `__setitem__` is up for grabs, as this no longer serves as a shortcut to `Treant.data`. I think a `Treant`'s "pythonic tree" functionality should come front and center, here, so this is already a great step in that direction.

**Comment by dotsdl** [comment]
Related: If we can figure out how to make tab-completion work for paths local to the `Treant` in its `__getitem__` method, that would be really powerful.

**Comment by kain88-de** [comment]
I just had a look into the IPython source. They have [special code-paths](https://github.com/ipython/ipython/blob/35fe1d3ec257ccfc0fef950bba44b19be671e52e/IPython/core/completer.py#L931) to make the tab-completion work for pandas and numpy objects. So I don't think we can do the completion without hacking IPython. We can ask though if it's possible to add completers.



> filtering on the Treant's stored metadata, in particular tags and categorie

Yes that be great. But I haven't set any metadata nor have i figured out how it works (mostly due to a lack of time). The posted solution above works good for me so far. But it is definitely lacking as a general purpose tool.

**Comment by kain88-de** [comment]
I've just came across [tinyDB](http://tinydb.readthedocs.org/en/latest/getting-started.html#basic-usage).

It's a simple key:value store that uses json and supports queries. It is a single dependency and might actually help querying for views with arbitrary metadata searches.

**Comment by dotsdl** [comment]
@kain88-de neat! I had a brief go with it, but I honestly don't have a clear idea yet of what we might be able to use it for. Perhaps if we decide on a separate `Treant.meta` limb that can add metadata to directories in the Treant's tree it would make sense to use this as the per-file backend?

**Comment by dotsdl** [comment]
Check out the [View](http://datreant.readthedocs.org/en/develop/views.html) object, which basically works as a Bundle for Trees and Leaves. If you import `datreant.data.attach` you'll be able to access data from a View using the same aggregation scheme that Bundle uses for pulling datasets from Treants.

If this satisfies, I'd like to close this issue for now.

**Comment by dotsdl** [comment]
Note that [``datreant.data`` docs](http://datreantdata.readthedocs.org/en/develop/) are next on my list after we hit release of this package, so using Views with the ``AggData`` limb will be detailed there.

**Comment by dotsdl** [comment]
Closing.
