### ISSUE TITLE
Drop pytables backend in favor of json?

### ISSUE THREAD

**Issue by dotsdl** [datreant/datreant.core#31]
I recently finished work on JSON backends for `Treant` and `Group` state files; the current status can be checked out on the [`exp-serial_backends`](https://github.com/datreant/datreant/tree/exp-serial_backends) branch. This was a follow-up to the work I had done previously but never quite finished on the YAML backend (this also works).

What I *didn't* expect was better performance on the part of JSON over the HDF5 format (see this [gist](https://gist.github.com/dotsdl/0f6676ce8358d482ea57) for some quick comparisons), although in hindsight it makes sense given that for storing and retrieving a few strings deserializing JSON is less costly than dealing with the HDF5 library, which is better for long reads of large datasets. It gave me a thought:

**Should we drop pytables as a backend in favor of JSON?**

I'm leaning in favor of this conclusion, for several reasons:
1. Since state files only store metadata consisting of tags and categories (at the moment), and since these probably number < 100 for a given `Treant`, performance is better than HDF5.
2. State files are human-readable with any text editor, and also grepable. :D
3. JSON is a serialization format, so streaming a state file through a pipe is trivial. Anything that deals in JSON can deal in state files.
4. No HDF5 or PyTables dependency.
5. JSON is more flexible in some ways. Instead of just tags and categories being stored as strings, they could also be floats, ints, booleans.
6. Unicode string storage, which does not work in HDF5 under PyTables, is no longer an issue. This was also the only barrier to making `datreant` [work fully under Python 3](https://github.com/datreant/datreant/issues/10).
7. No need for fixed-length strings, which is currently not handled elegantly in the PyTables backend.

Some downsides:
1. For derived classes in other packages such as `mdsynthesis.Sim`, storage of big things like arrays of `resnums` gets tricky and could degrade performance quickly (though with the new [`Topology` object](https://github.com/MDAnalysis/mdanalysis/tree/issue-363), `Universe` persistence may change greatly).

This move would remove a fundamental dependence on HDF5 and PyTables, which could allow splitting off `datreant.data` as a separate repo that upon imports gives the `Treant.data` limb for convenient storage. That's a separate issue, though, and merits its own discussion.

**Comment by dotsdl** [comment]
BTW, YAML isn't really worth using, even though it's more readable than JSON it does lose performance more steeply with file content due to its more complex grammar. It was as easy to implement as JSON so for now it's still there.

**Comment by kain88-de** [comment]
This is only for meta-data storage or for data-storage in general? If it is for data I would like to have the HDF5 backend as default. My current treant folder is about 20GB in size, I don't even wanna know how much that would be if I stored everything as plain-text.

**Comment by dotsdl** [comment]
This is only for the state file; the `Treant.data` interface, which stores things like `numpy` arrays and `pandas

**Comment by dotsdl** [comment]
Sorry...thumb slipped and posted. To be clear, data storage makes complete sense for HDF5 use, and that isn't changing. Using JSON for the state file instead of an HDF5 file (`Treant.<uuid>.h5` in a `Treant`'s directory), however, makes more sense I think.

**Comment by orbeckst** [comment]
JSON for metadata makes sense to me. 

But out of curiosity, do you think anyone will use datreant without the hdf5 storage?

**Comment by dotsdl** [comment]
@orbeckst I think datreant has potential beyond just an easy interface for storing numpy arrays and pandas dataframes, even though that was its original intention. I'm getting ready to merge in [`a branch`](https://github.com/datreant/datreant/tree/exp-dynamic_data) that has removed `datreant.data` from the core package, reducing the dependencies to `six` and `scandir` (which is now included in python 3.5, I believe). 

Issue #30 has spurred a lot of thought for what datreant should look like going forward, and I think `Treants` should at their most basic and general be directory trees with a pythonic interface and basic metadata storage/querying, as @kain88-de is interested in. Everything else, such as `datreant.data`, which provides the `Treant.data` and `Bundle/Members.data` limbs, should come a la carte, as these may have complex dependencies. The modularity of `Treants` and this style of packaging allows us to experiment freely without worrying about bloating the core `datreant` package.

For example, doing

```python
import datreant
```
gives the most vanilla of `Treant` objects. Also doing

```python
import datreant.data
```
gives all `Treant` classes a `.data` limb.

Domain-specific packages like [MDSynthesis](https://github.com/datreant/MDSynthesis) will still come "batteries-included", and won't require users to figure out which packages they need and what to import to make `Sim` objects work as they expect. The `datreant` packages is thus more of interest to developers, since it is more generic.

I'll shoot an email to the mailing list laying out this vision. I hadn't settled on it until the last week or so, and I'd be interested in discussion about anything I've failed to consider.
