### ISSUE TITLE
Remove Group in favor of Bundle only?

### ISSUE THREAD

**Issue by dotsdl** [datreant/datreant.core#39]
This issue was first broached in #35 [here](https://github.com/datreant/datreant.core/issues/35#issuecomment-172362148).

The `Group` object is a `Treant` that can store information on other `Treant`s, giving access to them as members. It was the first aggregation scheme built for `datreant`/`mdsynthesis`, predating the in-memory, non-persistent `Bundle` object that works similarly. There are fundamental technical problems with making `Group`s work reliably. 

Because they store paths to their members persistently, this information can quickly go out of date. The `Group` will go looking for members when they go missing, but this machinery gives no guarantee it can find them and old `Group`s can tend to be broken.

I propose we ditch this object in favor of `Bundle` usage, which can be persisted with a `Bundle.dump` method or similar, and reloaded later. I think we should move away from storing file paths and the like within state files since these tend to go stale more quickly than one might think.

I've been experimenting with this idea in the [`nogroups`](https://github.com/datreant/datreant.core/tree/nogroups) branch here, which builds on the ideas of #36 and begins work toward #23 and #30.

What do you think? What do you currently use `Group`s for, and would `Bundle` fill this need?

**Comment by kain88-de** [comment]
Yes I'm very much in favor of this idea.

[**There should be one-- and preferably only one --obvious way to do it.**](https://www.python.org/dev/peps/pep-0020/)

**Comment by orbeckst** [comment]
If groups go, where do I store analysis results over groups?
What happened to the idea of datreant/mds being able to find its members?

**Comment by dotsdl** [comment]
So, I gave this a long hard think over the last couple of weeks, and after also fixing a bug in `Group`'s member-finding functionality related to the HDF5 -> JSON migration, I've concluded that `Group`s really are extremely useful. They're also less fragile than I believed when I filed this issue (in frustration).

In short, `Group`s are here to stay. Removing them would be a loss of functionality that doesn't find form in a better alternative.

Also, `Group.members` is now a subclass of `Bundle`, so in a sense we're still conforming to the Zen. :P

**Comment by dotsdl** [comment]
Closed, but happy to reopen in case more discussion is needed.

**Comment by dotsdl** [comment]
See #130.

**Comment by dotsdl** [comment]
Resolved by #130.
