### ISSUE TITLE
Complete test coverage for AggTags

### ISSUE THREAD

**Issue by dotsdl** [datreant/datreant.core#46]
`datreant.core.agglimbs.AggTags` currently has placeholders for tests in `datreant.core.tests.test_collections.TestBundle`, but these need to be filled in to actually do anything. Help wanted.

**Comment by dotsdl** [comment]
@sseyler you interested? Would be a similar deal to building the tests for `AggCategories`, but simpler by comparison.

**Comment by sseyler** [comment]
@dldotson I'm definitely interested. Do you have a time frame for completion, or is it just the 0.7.0 milestone?

**Comment by dotsdl** [comment]
These don't have to get in before first release (later today). We should focus on getting the test coverage back up for the next release, though, so this is part of that. Probably within the next 1.5 months.

**Comment by dotsdl** [comment]
@sseyler are you still down to complete the test coverage for ``AggTags``? I did some work on it while on the plane last week, but didn't finish by any means.

**Comment by sseyler** [comment]
@dotsdl I'm going to try to get to it by this evening or tomorrow morning/day. I'll keep you updated.

**Comment by sseyler** [comment]
Added `test_tags_filter()` and `test_tags_fuzzy()` to *test_collections.py*. There may be a few redundant checks in `test_tags_fuzzy()`; may also want to add stuff to `test_tags_filter()` and `test_tags_fuzzy()` if coverage incomplete.

Still have to write tests for `test_tags_set_behavior()` and `test_tags_getitem()`.

**Comment by dotsdl** [comment]
Cool, can you open a PR? Add "WIP" to the front to let me know that it's a work-in-progress and shouldn't be merged until you're ready. This lets me have a look at what's there.

**Comment by sseyler** [comment]
What is the desired behavior of `__getitem__()` in `Tags`? Just need a bit of clarification!

According to the `__getitem__()` code in *limbs.py*:

```
if isinstance(value, set):
    # a set of tags gives only members WITHOUT ALL the tags
    # can be used for `not`, basically
    fits = not all([self[item] for item in value])
```

The wording suggests to me a *different* behavior than what's currently implemented. The current behavior is such that if *any* of the tags in a `set` provided to `__getitem__()` are *not* present, then return `True`; in other words, return `True` if at least one of the tags provided in the `set` isn't present in the Treant. The following returns `True`:

```
t = datreant.core.Treant('t')
t.tags.add('cat', 'dog', 'mouse')
t.tags[{'cat', 'catdog'}]
```

To get `False`, *each one of the tags in a `set` provided to `__getitem__()`' must *not* be present in a Treant; that is, if at least one of the tags is present, then we should get `True`.

It seems like either:

1. the wording in `__getitem__()` in *limbs.py* needs to be fixed (*# a set of tags gives only members WITHOUT ANY of the provided tags*), OR
2. the current behavior is different than intended.
