### ISSUE TITLE
provide conda packages

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.core#49]
Since MDAnalysis has joined the conda hotness I thought datreant could do the some. I got packages for all dependencies already except for scandir.

https://anaconda.org/kain88-de/packages

**Comment by dotsdl** [comment]
Awesome! Yeah, I have no experience building conda packages so this is much appreciated! Should we make a `datreant` conda channel to host these on?

**Comment by kain88-de** [comment]
That would make it look more official

**Comment by dotsdl** [comment]
Yeah, and with [datreant.data](https://github.com/datreant/datreant.data) almost ready for release (later today; finishing up [docs](http://datreantdata.readthedocs.org/en/develop/)), it would give us a nice hub for conda distribution.

Is setting up the conda channel something I should do? You're the expert in this domain. :D

**Comment by kain88-de** [comment]
I think we can also publish all of this on the MDAnalysis channel

**Comment by dotsdl** [comment]
I made a datreant org on the Anaconda cloud, and added you as an owner. I think this will work better than filling up the MDAnalysis channel. https://anaconda.org/datreant

Anything in particular you'd like me to do to share the load? Haven't messed with building conda packages and pushing them to the Anaconda cloud, but happy to follow your lead here.

**Comment by kain88-de** [comment]
I'm just creating a vagrant box that is compatible with the manylinux PEP.  If you have experience with that I appreciate help.

**Comment by dotsdl** [comment]
Thanks @kain88-de for putting these together. We now have conda packages on the [datreant](https://anaconda.org/datreant) conda channel!
