### ISSUE TITLE
copy treants on remote machines

### ISSUE THREAD

**Issue by gabrielelanaro** [datreant/datreant.core#58]
Hi, as a HPC user, I often find myself generating input directories (like for gromacs) and then uploading and running on a HPC cluster.

Is this use case covered? (or are there any plans for that use-case?)

**Comment by dotsdl** [comment]
Hey @gabrielelanaro, it's perfectly fine to copy Treants around, but at the moment there don't exist any built-in mechanisms for doing so. There are discussions on this front (#51, #54), but not anything explicit planned. If you could describe your use case and needs, or perhaps even how you would prefer copy/transfer functionality to work, that would help us move toward a good solution.

**Comment by kain88-de** [comment]
I do that regularly. I'm running simulations on an HPC cluster and afterwords collect the observables I'm interested in into a `datreant`. Afterwards I use rsync to copy the datreant folder onto my local machine and start my analysis. That works very well for me.

**Comment by gabrielelanaro** [comment]
I'll jot down some ideas that could simplify the workflows discussed above:

Let's say you're running stuff on a cluster and you want to peek on the result/status of some analysis. One thing you could do is mount the location as a remote filesystem (sshfs) and initialize a treant on that. While one can do things manually..one can also use the concept of a "remote treant".

```
t = RemoteTreant("ssh://user@host:~/projects") # This will mount this remote location using sshfs in local fs
# After that you could just read stuff off the treant
# if you want to make a copy, you could just
local_treant = t.clone('other/location')
```

Another idea could be using some syncronzation as mentioned in the other thread:

```
t = Treant('datreant')
t.rsync("ssh://....", include='', exclude='')
```

This could be a very clean approach, there are some problems on how to do the sync behaviour. 

-  sync based on timestamps?
- specify explicitly sync strategy?

**Comment by dotsdl** [comment]
@gabrielelanaro I've been chewing on this all week, and I think in the near term we should build out local copy functionality (#54) . As you mentioned, in combination with filesystem mounting schemes like ``sshfs``, this already can get us pretty far in making copying things around easier.

The idea of a ``RemoteTreant`` is interesting, but it would require some major work to implement. Also, it would require some careful thought to have a shot at being reasonably performant. Some issues I can think of:

1. Would we open an SSH connection (probably with ``paramiko``) every time a property (such as ``tags``) is called? This would be slow. Would we keep a line open for the whole Python session and funnel all ``RemoteTreant`` traffic through it? This might work, but it could get complex.
2. How would downstream packages (such as [MDSynthesis](https://github.com/datreant/MDSynthesis)) be able to take advantage of these? If ``Treant`` itself could operate in a remote mode, this might be mostly automatic, but that would be a major refactor of the core object. We should avoid this for now.

If you're interested in the ``RemoteTreant`` idea, we could begin experimenting in a ``datreant.remote`` subpackage. This gives the freedom to play around without affecting ``datreant.core``, and depending on the result things may get merged back into core if they make sense there.

As for ``rsync``, that is probably easier to get going. As I mentioned in #51 there doesn't seem to be a nice Python interface to rsync, but that doesn't mean we can't make one that's minimally useful for us here. Are you interested in helping to prototype this? I'm happy to help shepherd this along (I would definitely use it myself).

**Comment by gabrielelanaro** [comment]
That sounds like a reasonable plan, I can help on the rsync part soon enough (at the moment I'm in paper-writing madness), you think the rsync part should be part of core? If so I can work on a PR

**Comment by kain88-de** [comment]
My use-case 

1. Collect a bunch of observables on the cluster into a treant
2. copy that with `rsync -avzu --progress -h cluster:folder/to/datreant .` to my workstation

works perfectly without hitches for me. The `-u` flag ensures that only changed bits are copied by rsync. Of course I then always keep a complete copy of the treant on my workstation. But that is OK for me since it only contains processed data (8GB vs 500GB raw data).

About the syncing with a remote. Be very very careful with that. Syncing arbitrary files is an incredible hard thing to do.  Another good option for you might be rather using something like [git-annex](http://git-annex.branchable.com/) to selectively update and checkout parts of a treant.

**Comment by dotsdl** [comment]
@gabrielelanaro if you want to rapidly prototype it, by all means do it in core. We can work on placement later, and it may end up in a subpackage depending. We'll cross that bridge when we get there. Should be really useful!

**Comment by dotsdl** [comment]
@gabrielelanaro I'd be partial to an API roughly like [this](https://github.com/datreant/datreant.core/issues/51#issuecomment-202136077), but happy to see what comes out. If it can natively work with Bundles/Views for includes/excludes, that would be sweet and really versatile.

**Comment by gabrielelanaro** [comment]
In terms of API, the syncing could technically be a method of Tree?

I though about a few useful options, we can troubleshoot some potential problems

```python
        # Let's assume we have an existing tree
        dtr.Tree("sequoia").makedirs()
        
        # We create a new tree
        t = dtr.Tree('sequoia2')
        
        # Options 
        t.sync('sequoia', 
               mode='download', 
               compress=True, 
               backup=True,
               dry=True, 
               include=["*.txt"],
               exclude=[])
        
        # Upload content to sequoia
        t.sync('sequoia', mode='upload')
        
        # Download content from sequoia
        t.sync('sequoia', mode='download')
        
        # Remote sync OPTION 1
        t.sync('sequoia2', dir='/home/ubuntu/projects', host='127.0.0.1', user='xxx', password='xxx')
        t.sync('sequoia2', dir='/home/ubuntu/projects', host='127.0.0.1', user='xxx', key='./cloud.pem')
        
        # Maybe it's easier to use a simple string for host names?
        t.sync('sequoia2', host='ubuntu@127.0.0.1:/home/ubuntu/projects', port=22)
```

**Comment by dotsdl** [comment]
Hi @gabrielelanaro; just recently moved (real life problems), so just now getting plugged back into everything.

I really this so far. Do you have a starting point of the implementation? We can open a WIP (work-in-progress) PR with anything you currently have and go from there. I think this kind of functionality would be hugely useful.

**Comment by dotsdl** [comment]
@gabrielelanaro since your PR is now merged, does this address this issue sufficiently to close? I'm sure there will be rough edges here and there, but we can work through these as they are found.

**Comment by gabrielelanaro** [comment]
Yes that's good. I'll make a new PR to refine the code when I come back
from vacation :)

**Comment by dotsdl** [comment]
Awesome @gabrielelanaro. We definitely need complete docstrings for `datreant.core.rsync.rsync` and `datreant.core.trees.Tree.sync`. These especially need to make clear the slight deviation from rsync's own include/exclude semantics.
