### ISSUE TITLE
Main datreant package can't be found on PyPi

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.core#59]
`pip search datreant` returns no result.

**Comment by dotsdl** [comment]
It's definitely there: https://pypi.python.org/pypi/datreant.core

However, yeah, apparently searching with pip, even doing:

    pip search datreant.core

gives nothing. Perhaps it's the `.` in the name that fouls it up?

**Comment by dotsdl** [comment]
Related: doing ``pip search mdsynthesis`` gives nothing, too.

Am I missing some kind of special tags in ``setup.py`` to get PyPI to properly index the package?

**Comment by kain88-de** [comment]
I can install it from PyPi as well. It's just the search that doesn't work

**Comment by kain88-de** [comment]
Possible unrelated to that. TAB completion in ipython doesn't work correctly for me.
Typing `import datreant.c` I expect that it would complete to `import datreant.core`. instead I just get the warning-bell of the terminal telling me that no completion is available.

**Comment by dotsdl** [comment]
Also perhaps related: [recent MDAnalysis releases don't show up, either](https://pypi.python.org/pypi?%3Aaction=search&term=mdanalysis&submit=search).

From what I've seen, it looks like this is perhaps ongoing (see [this issue](https://bitbucket.org/pypa/pypi/issues/326/some-packages-not-showing-up-when) and its linked issues). :/

**Comment by kain88-de** [comment]
They are also building and update to PyPi called warehouse. You can Google it a beta is already online.

**Comment by orbeckst** [comment]
Regarding issues with `pip search`: My suspicion is that their search index is just very much behind...
```
$ pip search mdanalysis
simpletraj (0.3)          - Lightweight coordinate-only trajectory reader based on code from GROMACS, MDAnalysis, VMD.
MDAnalysisTests (0.13.0)  - Python tools to support analysis of trajectories (test cases)
  INSTALLED: 0.15.0
  LATEST:    0.13.0
MDAnalysis (0.13.0)       - An object-oriented toolkit to analyze molecular dynamics trajectories generated by CHARMM, Gromacs, NAMD, LAMMPS, or
                            Amber.
  INSTALLED: 0.15.0
  LATEST:    0.13.0
```

MDAnalysis 0.13.0 hasn't been "the latest" in a while...

**Comment by dotsdl** [comment]
It now looks like we can find our packages in PyPI now. Closing.
