### ISSUE TITLE
hide pytables naming NatrualNameWarnings

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.core#62]
I have a dataframe containing names like `out-99`. This means I can't use it as a python attribute name in pandas and neither in pytables. Saving the treant pytables gives an annoying `NaturalNameWarning: object name is not a valid Python identifier: 'out-99_dtype' ...`. Since this is only internally handled by datreant it would be good to silence those warnings.

**Comment by dotsdl** [comment]
This is a [``datreant.data``](https://github.com/datreant/datreant.data) issue. If it's not much trouble, would you mind moving this there?
