### ISSUE TITLE
package names may not contain dots: datreant-core

### ISSUE THREAD

**Issue by orbeckst** [datreant/datreant.core#64]
I came across pypa/pip#3666 which says that `pip` 8.1.2 now correctly implements [PEP 503](https://www.python.org/dev/peps/pep-0503/), in particular the [normalized names](https://www.python.org/dev/peps/pep-0503/#normalized-names):

> The name should be lowercased with all runs of the characters . , - , or _ replaced with a single - character. 

The `datreant.core` package should be renamed to `datreant-core`. (And maybe then it will be possible to find it on PyPi...)

**Comment by orbeckst** [comment]
See also https://www.continuum.io/blog/developer-blog/new-pip-812-release-leaves-anaconda-cloud-broken-fix-progress

**Comment by kain88-de** [comment]
Oh I also noticed that TAB-completion doesn't work in IPython to load `datreant.core` I have to type it myself to get correct completions later on.

**Comment by dotsdl** [comment]
@kain88-de I'm not sure what that issue is, but it might have to do with how IPython populates its autocorrect for imports. Since ``datreant`` is a namespace package, and not a "real" package, it might just choke on this. In which case, it's a shame, but it's a problem that would need to be addressed in IPython itself.

**Comment by dotsdl** [comment]
Thanks @orbeckst, but it looks like packages like ``datreant.data`` download and install just fine using pip 8.1.2 despite the `.` in the name. Not sure I understand if anything needs to change? Sounds like [something low-level](https://github.com/pypa/pip/issues/3666#issuecomment-218452131)?

**Comment by dotsdl** [comment]
Closing for now. If things appear to break later with regard to `pip` installs, we'll reopen.
