### ISSUE TITLE
human readable tag selection.

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.core#65]
According to the current scipy paper and I assume docs the logical operator to filter tags on a Bundle is the type of the object I'm passing. While need as code this is actually hard to read. I'd appreciate some logical operators with some DSL supporting only `or`, `and` and `nand` (not and). Then one could filter with

``` python
b.tags['(building and furniture) nand paper']
```

This will only select _oak_ and _maple_ in the paper example. The current equivalent is unreadable and I'm not sure mine is correct.

``` python
b.tags[{['building', 'furniture'], ['paper']}]
```

**Comment by dotsdl** [comment]
Doing "building *and* furniture" will get an empty bundle in the paper example, since there are no Treants with **both** "building" *and* "furniture" as tags. If you want both ``oak`` and ``maple``, you could do

> ('building' or 'furniture') and not 'paper'

which can be written as a tag expression as:

```python
b.tags[[('building', 'furniture'), {'paper'}]]
```
I agree that these are a bit to get used to (and @orbeckst doesn't like them, either). I think we could benefit from a DSL as you suggested. It **shouldn't** be too hard to do with something like ``pyparsing``, or building one similar to that in MDAnalysis.

Anyone else have any thoughts? @datreant/coredevs?

**Comment by orbeckst** [comment]
I’ll state for the record that I think that the boolean tag selections are an abuse of syntax.

However, I encourage David to present it at SciPy and see what the reaction is.

**Comment by kain88-de** [comment]
I'll have a look at it. I always wanted to implement a small parser

**Comment by orbeckst** [comment]
> On 1 Jun, 2016, at 23:49, kain88-de <notifications@github.com> wrote:
> 
> I'll have a look at it. I always wanted to implement a small parser

Have a look at pyparsing!

**Comment by jbarnoud** [comment]
In the same order of idea, it would be nice to be able to do the same with categories. Right now, the following would change my life:

```
new_bundle = bundle.categories['force_field == gromos53a6 and target_concentration > 100]
```

**Comment by richardjgowers** [comment]
Yeah these don't seem intuitive, someone could naively put in a set of what they want (because they used a set operation to reach that point) and end up with the opposite of what they wanted. +1 for readable strings and scrapping this.

**Comment by kain88-de** [comment]
https://gist.github.com/kain88-de/9728e5b76082d9c3336ce840cb3195b5


I wrote an example parser based on a example in the pyparsing book.  Should be easy enough as a drop. Just run the parser when we find in getitem that the object is a string

**Comment by kain88-de** [comment]
I noticed that a parser with `not`, `and` and  `or` isn't easily transferable to datreants `nand` construct. The `nand` is also a bit of a clutch when I want to translate it to a normal string. If I want to negate just one  word  then `nand word` just doesn't make much sense. In general being able to work with a normal `not` would be nicer. But them might require to rething the `set`, `list`, `tuple` selection syntax

**Comment by orbeckst** [comment]
Totally random comment and probably besides the point but I vaguely remember something from Boolean algebra/circuits that you can create *any* logic gate from NAND gates only. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by kain88-de** [comment]
Yes with `NAND` one can rebuild all logic gates. The problem I had is just that `{a, b}' is not the same as `[{a}, {b}]` and I still don't really know why. So the `{}` might not implement a real NAND?

**Comment by kain88-de** [comment]
BTW I now have a implementation that works correct for me. I updated the gist with it.
