### ISSUE TITLE
pathlib isn't supported anymore

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.core#67]
Looks like pathlib is not actively maintained anymore. They recommend an updated pathlib2 library

https://pypi.python.org/pypi/pathlib2/

**Comment by dotsdl** [comment]
Thanks @kain88-de! From [this discussion](https://github.com/mcmtroffaes/pathlib2/issues/8#issuecomment-162873095), it looks like what we need is to just use ``pathlib2`` as our import instead of ``pathlib``. Since we want to support < python 3.4 for now still, we'll do this.
