### ISSUE TITLE
Improve documentation of rsync functionality

### ISSUE THREAD

**Issue by dotsdl** [datreant/datreant.core#73]
We need complete docstrings for `datreant.core.rsync.rsync` and `datreant.core.trees.Tree.sync`. These especially need to make clear the slight deviation from rsync's own include/exclude semantics.

**Comment by dotsdl** [comment]
@gabrielelanaro are you interested in taking this on? You're most familiar with the code here. :D

**Comment by gabrielelanaro** [comment]
for sure, that's part of the clean-up
