### ISSUE TITLE
Submit and maintain conda recipes on conda-forge

### ISSUE THREAD

**Issue by dotsdl** [datreant/datreant.core#85]
[conda-forge](https://conda-forge.github.io/) is a community-driven effort to supply well-maintained conda recipes for packages in the (mostly scientific) python ecosystem. It also provides automated building upon release on multiple platforms (Linux, OSX, Windows), testing, and submission to the Anaconda cloud.

I suggest we follow the instructions for adding our datreant conda recipes to conda-forge. This could save us the hassle of building these ourselves on every release, and is the first step toward testing on more platforms. 

I've already done the first step, which is to clone the [staged-recipes](https://github.com/datreant/staged-recipes) repo, but I've gone no further so far.

**Comment by dotsdl** [comment]
@kain88-de do you have interest in this? You're the most well-versed in conda, and this might help to ease your burden here.

**Comment by kain88-de** [comment]
sure I can have a look into it. It will take some time though.

**Comment by kain88-de** [comment]
conda forge looks nice and I think I understand how they build all the different os versions now.

@dotsdl do you know if there is some mailing list for conda-forge I can't find anything on the website

**Comment by kain88-de** [comment]
I'll try adding the missing dependencies first and then we see to add all datreant packages one after the other.

**Comment by kain88-de** [comment]
See https://github.com/conda-forge/staged-recipes/pull/1123

**Comment by dotsdl** [comment]
@kain88-de I can't find a mailing list, and I think that's because they do all their communication through the github org, in particular the [website issue tracker](https://github.com/conda-forge/conda-forge.github.io/issues). Phillip Elson gave [a good talk at SciPy](https://www.youtube.com/watch?v=Hacl_YFzZOw) highlighting the motivations and the machinery behind how conda-forge works; this might be of use.

**Comment by dotsdl** [comment]
@kain88-de thanks for doing this! It looks ``fuzzywuzzy``, ``python-Levenshtein``, ``six``, and ``pathlib2`` are already there, so we only need ``asciitree`` and ``scandir`` for making ``datreant.core`` work.

**Comment by kain88-de** [comment]
asciitree is in. Now on to scandir

**Comment by dotsdl** [comment]
Awesome. Hope it wasn't much of a hassle, and that this makes the `conda` end of things easier to maintain. Thanks @kain88-de!

**Comment by kain88-de** [comment]
nope not really. I'll add the @datreant/coredevs as maintainers for the datreant packages when I submit them

**Comment by dotsdl** [comment]
@kain88-de now that conda-forge/staged-recipes#1144 has been merged, is this issue closed?

**Comment by kain88-de** [comment]
Data is missing.

**Comment by kain88-de** [comment]
https://github.com/conda-forge/datreant.data-feedstock

We are there now. Everything except mdsynthesis is in.

**Comment by dotsdl** [comment]
Awesome, thanks @kain88-de for making this happen despite the lengthy process. Hopefully this makes maintaining conda builds that much easier for the foreseeable future.
