### ISSUE TITLE
Mac OS X tests on Travis CI

### ISSUE THREAD

**Issue by dotsdl** [datreant/datreant.core#87]
If we can, we should try and get Mac OSX builds running on Travis CI. This has been done for [MDAnalysis](https://github.com/MDAnalysis/mdanalysis/blob/develop/.travis.yml) and since we don't need conda to build out a decent environment for the dependency-light `datreant.core`, we could probably lift a lot less from there to get this working.

**Comment by kain88-de** [comment]
You can use the ci-helpers from astropy as well. We started now to use it for MDAnalysis

**Comment by kain88-de** [comment]
https://github.com/astropy/ci-helpers

**Comment by kain88-de** [comment]
since we use only python function this doesn't add much value. Given that OSX testing on Travis also draws a lot of resources for them that they have trouble keeping up with I say linux is enough.
