### ISSUE TITLE
Add license to sdist with MANIFEST.in

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.core#94]
The source package we distribute in PyPa doesn't include the BSD license. If we add a `MANIFEST.in` we can tell setuptools to include the LICENSE file from the git repo into the final package.

@dotsdl can you do this? You have more experience with python packaging.

**Comment by jakirkham** [comment]
Honestly this is pretty simple to do. Just add the following to `MANIFEST.in`. If you don't have `MANIFEST.in`, this is all it will contain.

```
include LICENSE
```

**Comment by dotsdl** [comment]
@kain88-de yeah no problem. Thanks @jakirkham for the recommendation; I'll get this in shortly.

**Comment by dotsdl** [comment]
Just pushed a `MANIFEST.in` file into the top-level directory. Is this enough?

**Comment by kain88-de** [comment]
@dotsdl can you also add it to the other datreant packages

**Comment by dotsdl** [comment]
@kain88-de no problem. Will do.

**Comment by jakirkham** [comment]
LGTM. Should be able to test by doing `python setup.py sdist` and then extracting the tarball in the `dist` directory. If you see `LICENSE` in it, then it worked.

**Comment by dotsdl** [comment]
@kain88-de added MANIFEST.in in each of `datreant.data` and `mdsynthesis`.
