### ISSUE TITLE
attach limbs to a Bundle

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.core#96]
How can I attach the data limb for all Treants in a Bundle? I know I could just use `import datreant.data.attach` but I would like to know how I specify with eq `discover` that data should be attached to all Treants it finds.

**Comment by dotsdl** [comment]
@kain88-de you can attach the `Data` limb directly to the `Bundle`, and this will add it to all member `Treant`s:

```python
import datreant.core as dtr
import datreant.data

b = dtr.discover()

b.attach('data')

# this will now work
b.data
```

Does that help? Sorry for the delay in getting such a simple answer out; trying to finally triage some issues between writing.

**Comment by kain88-de** [comment]
that is nice. Is this documented?

**Comment by dotsdl** [comment]
In a fit of foresight on my part, apparently [yes](http://datreantdata.readthedocs.io/en/develop/views_bundles.html#aggregating-datasets-with-views-and-bundles). :D

**Comment by kain88-de** [comment]
blessed are the people who are able to read.

**Comment by dotsdl** [comment]
@kain88-de it happens to me all the time. :P
