### ISSUE TITLE
filter to access only specific named limb data.

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.core#98]
Since I'm storing more then one observable per simulation in a treant I have a
hard time accessing only one observable from a bundle. Suppose I always store
rmsd and radius of gyration in the treant. Then it would be nice if I can write
code like this to quickly query only the 'rmsd' data to example find the maximum
rmsd.

```python
b = dtr.discover('processed-data')
# This is a bundle of treants that only co
max = -1
for rmsd in b.data['rmsd']:
    if rmsd.max() > max:
        max = rmsd.max()
```

I'm not sure yet what the best object is that `b.data['rmsd']` should return.
But I would like that it is iterable and has the same tags/categories as the
treants the 'rmsd' files are coming from.

Right now I have to use the following code.

```python
b = dtr.discover('processed-data')
# This is a bundle of treants that only co
max = -1
for rmsd_treant in b:
    rmsd = rmsd_treant.data['rmsd']
    if rmsd.max() > max:
        max = rmsd.max()
```

This is brittle because it will fail as soon as a treant doesn't have a 'rmsd`
data member.

It is also not easy to query what data objects are stored in a treant from a
bundle.

**Comment by dotsdl** [comment]
@kain88-de if the stored `rmsd` data is a `DataFrame`, you can already extract a concatenated, multi-indexed `DataFrame` for all `Treant`s in a `Bundle` directly with ``b.data['rmsd']``. Try this:

```python
b = dtr.discover('processed-data')
b.data['rmsd'].max()
```
and this should work just fine. If each stored `rmsd` is a `numpy` array or a pure-Python object (such as a single number), then doing `b.data['rmsd']` will give you a dict, I think, which `uuid`s as keys.

Does that help? Or did I misunderstand a key piece of your explanation?

**Comment by kain88-de** [comment]
I'll have to try. I didn't know you can work on bundles like that. It will make some things easier though.

**Comment by dotsdl** [comment]
See the [relevant doc page](http://datreantdata.readthedocs.io/en/develop/views_bundles.html#multiindex-aggregation-for-pandas-objects) for more details on how to wield this functionality with grace. I do the kind of stuff you describe all the time to work with datasets across Treants with no fuss.
